[2023-01-25T12:01:07.319-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: raw_opt_t_statusconta.current_date scheduled__2023-01-24T15:00:00+00:00 [queued]>
[2023-01-25T12:01:07.797-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: raw_opt_t_statusconta.current_date scheduled__2023-01-24T15:00:00+00:00 [queued]>
[2023-01-25T12:01:07.797-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T12:01:07.797-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-25T12:01:07.797-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T12:01:08.467-0300] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): current_date> on 2023-01-24 15:00:00+00:00
[2023-01-25T12:01:08.473-0300] {standard_task_runner.py:55} INFO - Started process 1739522 to run task
[2023-01-25T12:01:08.477-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'raw_opt_t_statusconta', 'current_date', 'scheduled__2023-01-24T15:00:00+00:00', '--job-id', '1360', '--raw', '--subdir', 'DAGS_FOLDER/raw/dock_opt/raw_opt_t_statusconta.py', '--cfg-path', '/tmp/tmp5ibngw1s']
[2023-01-25T12:01:08.480-0300] {standard_task_runner.py:83} INFO - Job 1360: Subtask current_date
[2023-01-25T12:01:11.522-0300] {task_command.py:389} INFO - Running <TaskInstance: raw_opt_t_statusconta.current_date scheduled__2023-01-24T15:00:00+00:00 [running]> on host vm-airflow-01
[2023-01-25T12:01:14.050-0300] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=matheus.rodrigues@fortbrasil.com.br
AIRFLOW_CTX_DAG_ID=raw_opt_t_statusconta
AIRFLOW_CTX_TASK_ID=current_date
AIRFLOW_CTX_EXECUTION_DATE=2023-01-24T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-24T15:00:00+00:00
[2023-01-25T12:01:14.051-0300] {python.py:177} INFO - Done. Returned value was: 2023-01-25
[2023-01-25T12:01:15.379-0300] {taskinstance.py:1322} INFO - Marking task as SUCCESS. dag_id=raw_opt_t_statusconta, task_id=current_date, execution_date=20230124T150000, start_date=20230125T150107, end_date=20230125T150115
[2023-01-25T12:01:17.800-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 1360 for task current_date ((pyodbc.Error) ('40001', '[40001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Transaction (Process ID 222) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. (1205) (SQLExecDirectW)')
[SQL: UPDATE task_instance SET end_date=?, duration=?, state=?, updated_at=? WHERE task_instance.dag_id = ? AND task_instance.task_id = ? AND task_instance.run_id = ? AND task_instance.map_index = ?]
[parameters: (datetime.datetime(2023, 1, 25, 15, 1, 15, 379142, tzinfo=Timezone('UTC')), 8.057384, <TaskInstanceState.SUCCESS: 'success'>, datetime.datetime(2023, 1, 25, 15, 1, 8, 240924, tzinfo=Timezone('UTC')), 'raw_opt_t_statusconta', 'current_date', 'scheduled__2023-01-24T15:00:00+00:00', -1)]
(Background on this error at: https://sqlalche.me/e/14/dbapi); 1739522)
[2023-01-25T12:01:17.816-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-25T12:01:18.534-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
